name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -B deploy
          git add build -f
          git commit -m "Deploy build from $GITHUB_SHA" || echo "No changes to commit"
          git push origin deploy --force
